drop table user if exists;
create table user (
  id integer primary key GENERATED BY DEFAULT AS IDENTITY(START WITH 100),
  username varchar(50) not null,
  email varchar(50) not null,
  pw varchar(255) not null
);

drop table friends if exists;
create table friends (
  follower_id integer not null,
  followee_id integer not null
);

drop table message if exists;
create table message (
  id integer primary key GENERATED BY DEFAULT AS IDENTITY(START WITH 100),
  user_id integer not null,
  text varchar(160) not null,
  pub_date timestamp
);